### ISSUE TITLE
Cannot use upgrade command with JIT module loaded

### ISSUE THREAD

**Issue by november-kilo** [dworkin/lpc-ext#1]
After adding the jit module, cloud-server's `upgrade` command does not complete and I have to kill the mud.

**Comment by november-kilo** [comment]
I pulled a fresh cloud-server repo and it doesn't occur there. I must have messed up something. I'll close this.

**Comment by november-kilo** [comment]
I was wrong. The `upgrade` command works the first time, but not the second time.
```
> ls /lib
ChainedContinuation.c*    GMTime.c*                 String.c*
Continuation.c*           IntIterator.c*            StringBuffer.c*
ContinuationToken.c*      Iterable.c*               Time.c*
DelayedContinuation.c*    IterativeContinuation.c*  util/
DistContinuation.c*       Iterator.c*
> upgrade /lib/Time.c
Successfully upgraded:
  /lib/Time.c
> upgrade /lib/String.c

```

**Comment by dworkin** [comment]
@november-kilo 4d5cdc6fb2af9dbdf16ff4ea5d194caa56444ebc should fix this problem, please give it a try.

**Comment by dworkin** [comment]
When rebuilding the JIT compiler, please make sure to clear the cache.  Otherwise, the JIT compiler will assume that the previous JIT-generated code can be reused.

**Comment by november-kilo** [comment]
@dworkin Cleared cache and rebuilt. No problems with upgrade command. 👍

**Comment by dworkin** [comment]
Thank you for reporting this bug.
